PR#12
cgiroux86/test pull request #163
Opened 2021-04-22 20:56 UTC by cgiroux86

2021-04-22 21:18 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvQt-nE368XWtNgFxo:-MYvQt-o3lOGLW2Im31g:b-sgxs9e) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Here to block!


<!-- Sent from Reviewable.io -->

2021-04-22 22:43 UTC, girouxchris1017 reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)



<!-- Sent from Reviewable.io -->

2021-04-22 22:48 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYvlKQbCnuuGOUPME4J:bt0udk0) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

Let's try this again! 


<!-- Sent from Reviewable.io -->

2021-04-22 22:55 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvmoZQ-2P581GCayxE:-MYvmoZR88ZmfEr9mH6g:b-tylcg2) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This is not good!


<!-- Sent from Reviewable.io -->

2021-04-23 12:02 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYyaiNT09GAE99AqNh-:-MYyaiNU0JFJg7MlZFhn:b-kon2nw) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

Though I tried my best to believe


<!-- Sent from Reviewable.io -->

2021-04-23 12:41 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYyhVMl0qtNzYcLooRJ:-MYyhVMmEt74I1sIpgRP:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

TEST


<!-- Sent from Reviewable.io -->

2021-04-23 12:44 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYykZZ5DEmUn5JFPDjy:-MYykZZ6DwkfGxh-lsAt:bncwqnt) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Here's what I mean


<!-- Sent from Reviewable.io -->

2021-04-23 12:44 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)



<!-- Sent from Reviewable.io -->

2021-04-23 12:47 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MYylPTq28E_1XHzGE8-:bj3v68) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

HELLO WORLD :) 


<!-- Sent from Reviewable.io -->

2021-04-23 12:49 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)



<!-- Sent from Reviewable.io -->

2021-04-23 13:06 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYymTGhCnHGJjENjU3V:-MYymTGiAP6DwVS2vKkE:b-b0zk2m) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

If everyday goes like this.... 


<!-- Sent from Reviewable.io -->

2021-04-23 14:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 6 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/163#-MYz2Svf3aye3fgkomnr:-MYz2Svf3aye3fgkomns:bdl53j2) ([raw file](https://github.com/cgiroux86/test/blob/725d304439644e925b6d4a2c19dad5739bca37a4/mainfile1.js#L7)):*
> ```JavaScript
> console.log('4th commit');
> console.log('5th commit');
> console.log('6th commit');
> ```

Whisper words of wisdom.


<!-- Sent from Reviewable.io -->

2021-04-23 17:00 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @cgiroux86)

___
*[test.txt, line 1 at r4](http://localhost:8080/reviews/cgiroux86/test/163#-MYzfEvb418yfSqYcmuq:-MYzfEvc77XxpCFrTiLa:b-le40ky) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!!!
> ```

I think we want to be overly welcoming.


<!-- Sent from Reviewable.io -->

2021-04-23 17:02 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MYyqq-y6-ib9ulbt3yo:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

HELLO WORLD :) 
</blockquote></details>

Done.
___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYzfdCL6fIN52UFhYab:b3ajh0t) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Let's try this again! 
</blockquote></details>

Replying to your comment!
___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvNY2Q3eRzjmRnun_9:-MYvNY2R3CJS84FXqI7t:b32vvq) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Hi
___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvQt-nE368XWtNgFxo:-MYyqqlV-XL4K6-6vyQG:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Here to block!
</blockquote></details>

Done.
___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYykZZ5DEmUn5JFPDjy:-MYyqr27CPUv8VmvAxqI:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Here's what I mean
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 17:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYyhVMl0qtNzYcLooRJ:-MYzfo0fDPoPNJ37F2qF:boeyj2c) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

REPLYING!


<!-- Sent from Reviewable.io -->

2021-04-23 17:12 UTC, girouxchris1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYzhvdv1vAXi3eNAjpr:b-pp9n81) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Replying to your comment!
</blockquote></details>

Don't like it.


<!-- Sent from Reviewable.io -->

2021-04-23 17:13 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYzi5n7DFqDbzp8JtoZ:bb76mu4) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Don't like it.
</blockquote></details>

Why?


<!-- Sent from Reviewable.io -->

2021-04-23 17:14 UTC, girouxchris1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYziOBRAtEozsM6WdTy:btp9z2p) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Because I said so.


<!-- Sent from Reviewable.io -->

2021-04-23 17:14 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvlKQaCFWm7mVtZk7I:-MYziS8U0Abm-r9POYzs:b-5g6am7) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Because I said so.
</blockquote></details>

That's not a good answer.


<!-- Sent from Reviewable.io -->

2021-04-23 17:16 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MYzivoZ8UFWcDGFrwa1:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-04-23 18:01 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MYztAfkBhj37u8aB40F:-MYztAfl7we_rgNfm281:bbdehml) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> console.log('function added');
> console.log('third commit!!');
> ```

Why was this removeD?


<!-- Sent from Reviewable.io -->

2021-04-26 12:58 UTC, chg1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r4](http://localhost:8080/reviews/cgiroux86/test/163#-MYzfEvb418yfSqYcmuq:-MZDFaKFCvsn0VX2B4oy:bb76mu4) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

I think we want to be overly welcoming.
</blockquote></details>

Why?


<!-- Sent from Reviewable.io -->

2021-04-26 12:59 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r4](http://localhost:8080/reviews/cgiroux86/test/163#-MYzfEvb418yfSqYcmuq:-MZDFlskB3paZeu65ouO:b-g2h2vp) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I don't know yet, but it doesn't feel right.


<!-- Sent from Reviewable.io -->

2021-04-26 13:10 UTC, chg1017 reviewed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-04-26 13:35 UTC, girouxchris1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 6 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvNY2Q3eRzjmRnun_9:-MZDNzoaEClNNbPPr8iV:b2nhktp) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L6)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Hi
</blockquote></details>

OK.


<!-- Sent from Reviewable.io -->

2021-04-26 13:46 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZDQVrs0qhjXqkQlj1w:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.
___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYymTGhCnHGJjENjU3V:-MZDQV637gl_tggS1fAV:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

If everyday goes like this.... 
</blockquote></details>

Done.
___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvmoZQ-2P581GCayxE:-MZDQVRt5SJ7hPpvmK6Q:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

This is not good!
</blockquote></details>

Done.
___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/163#-MYz2Svf3aye3fgkomnr:-MZDQUkG9_bN3jEMHiqr:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/725d304439644e925b6d4a2c19dad5739bca37a4/mainfile1.js#L7)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Whisper words of wisdom.
</blockquote></details>

Done.
___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MYztAfkBhj37u8aB40F:-MZDQTR0AnFQUjHbwYDL:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why was this removeD?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-26 14:31 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZD_vS1DaooynnBLc-c:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-04-26 14:32 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZDa3z84_rOGTYvz9Nq:bt679l9) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Testing this out.


<!-- Sent from Reviewable.io -->

2021-04-26 14:34 UTC, chg1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZDaXWq3ldf8KjvsrgZ:b-8sugfy) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Testing this out.
</blockquote></details>

The rains going to wash away I believe


<!-- Sent from Reviewable.io -->

2021-04-26 14:39 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZDbjPpCBRU2oBJfBpM:b2nh8oq) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

The rains going to wash away I believe
</blockquote></details>

???


<!-- Sent from Reviewable.io -->

2021-04-26 14:44 UTC, chg1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/163#-MYz2Svf3aye3fgkomnr:-MZDck-XBE5LoRPxLwYR:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/725d304439644e925b6d4a2c19dad5739bca37a4/mainfile1.js#L7)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-04-26 14:44 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MYztAfkBhj37u8aB40F:-MZDcqr60Azt3Y0z5kG0:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-04-26 14:45 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 6 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 1 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdAdb0lKFloEydRYt:-MZDdAdcE3PGj8JJJcf_:b56xnrq) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L1)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> ```

Because maybe?


<!-- Sent from Reviewable.io -->

2021-04-26 14:46 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdMar27jVGN0tsd_r:-MZDdMasDEC-zDQY06gM:bo73evf) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

Necessary? 


<!-- Sent from Reviewable.io -->

2021-04-26 14:48 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdljc-YYf7Q8_WQ1o:-MZDdljc-YYf7Q8_WQ1p:b3m83gv) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L7)):*
> ```JavaScript
> console.log('4th commit');
> console.log('5th commit');
> console.log('6th commit');
> ```

too many?>


<!-- Sent from Reviewable.io -->

2021-04-26 14:52 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MYztAfkBhj37u8aB40F:-MZDeb1T5FejmmbktVDo:b-pp9n81) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Don't like it.


<!-- Sent from Reviewable.io -->

2021-04-26 14:57 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDfKT_C0sOxpTJ0Tyk:-MZDfKTa0pHDxY_Lopfm:b-ps7e2a) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> console.log('function added');
> console.log('third commit!!');
> ```

Feeling strong.


<!-- Sent from Reviewable.io -->

2021-04-26 15:00 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-04-26 15:17 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-04-26 15:21 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDlL1T3ds7guH7oFtz:-MZDlL1T3ds7guH7oFu-:bsobot3) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> console.log('function added');
> console.log('third commit!!');
> ```

I don't know.


<!-- Sent from Reviewable.io -->

2021-04-26 15:25 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDfKT_C0sOxpTJ0Tyk:-MZDmAXP8FypLESghSi0:b-d5bpas) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Feeling strong.
</blockquote></details>

Still running.


<!-- Sent from Reviewable.io -->

2021-04-26 15:34 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 10 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 2 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDoMGw2Y6FInmPGEyW:-MZDoMGxCItK0zm0MeFC:bnvx9hn) ([raw file](https://github.com/cgiroux86/test/blob/e8f366f5dc5f916751fa6c443f4f8c0c200fef71/newFile.js#L2)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> console.log('function added');
> ```

TESTING


<!-- Sent from Reviewable.io -->

2021-04-26 16:09 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/163#-MYz2Svf3aye3fgkomnr:-MZDwJ7HC6Re_GdVJbnH:b-who9wv) ([raw file](https://github.com/cgiroux86/test/blob/725d304439644e925b6d4a2c19dad5739bca37a4/mainfile1.js#L7)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Closing time.


<!-- Sent from Reviewable.io -->

2021-04-26 16:18 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 10 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYymTGhCnHGJjENjU3V:-MZDyIGE8RJFS6rY9hA6:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2021-04-26 17:02 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 11 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r7](http://localhost:8080/reviews/cgiroux86/test/163#-MZE7Wl-64WDRdiQ2NYy:-MZE7Wl0BfGy-SFW6KwR:bjdh22p) ([raw file](https://github.com/cgiroux86/test/blob/660d1caa5c5683aba18672310d73155f7bd6b68e/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('EVERYDAY!!!');
> ```

Timestamp test


<!-- Sent from Reviewable.io -->

2021-04-26 17:09 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 11 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[newFile.js, line 2 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDoMGw2Y6FInmPGEyW:-MZE99Xw9BWV7KMR-bJH:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/e8f366f5dc5f916751fa6c443f4f8c0c200fef71/newFile.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

TESTING
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2021-04-26 17:14 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 12 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZEA9YkAfXHuKMIfItS:-MZEA9YkAfXHuKMIfItT:b5952i6) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
> ```JavaScript
> console.log('The newest of new of brand new for testing in PROD!!!!!!!!!!');
> console.log('function added');
> console.log('third commit!!');
> ```

Another blocking disposition


<!-- Sent from Reviewable.io -->

2021-04-26 17:16 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 12 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYylPTpDTPLKDe6K4jz:-MZEAZlQArlgnvx0Xt5q:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

???
</blockquote></details>

Done.
___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdMar27jVGN0tsd_r:-MZEA_1z4PVW6cY2vJzY:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Necessary? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-26 17:32 UTC, chg1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 13 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MYztAfkBhj37u8aB40F:-MZEEQ405Ptu_sYettMB:b2xz6b9) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Don't like it.
</blockquote></details>

PARTICIPANTsZ


<!-- Sent from Reviewable.io -->

2021-04-26 17:35 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 13 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 6 at r7](http://localhost:8080/reviews/cgiroux86/test/163#-MZEF4gQEIeIXwJp230O:-MZEF4gR-SPmgHk1AIls:bk0k3zo) ([raw file](https://github.com/cgiroux86/test/blob/660d1caa5c5683aba18672310d73155f7bd6b68e/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Another test


<!-- Sent from Reviewable.io -->

2021-04-26 18:11 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 13 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/163#-MZEN7r_2KxmUpTfZpMh:-MZEN7ra81YHTuZjPban:b-n24k5m) (no related file):*
Main blocker.

---


<!-- Sent from Reviewable.io -->

2021-04-26 19:37 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 13 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/163#-MZEN7r_2KxmUpTfZpMh:-MZEfuXZCNK4im-rAd6M:b-896fix) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Main blocker.
</blockquote></details>

Done.

---
___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYymTGhCnHGJjENjU3V:-MZEfoFV0T65wDRNZ5gE:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.
___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MYvmoZQ-2P581GCayxE:-MZEfrm312mExp48RM46:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/2abae257edbc0924580d34f46fe4275373b8f5c4/mainfile1.js#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[mainfile1.js, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdljc-YYf7Q8_WQ1o:-MZEfr9g0pRDkdWl7zb_:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/mainfile1.js#L7)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

too many?>
</blockquote></details>

Done.
___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/163#-MYz2Svf3aye3fgkomnr:-MZEfomn2StrmlmSm0lA:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/725d304439644e925b6d4a2c19dad5739bca37a4/mainfile1.js#L7)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Closing time.
</blockquote></details>

Done.
___
*[mainfile1.js, line 6 at r7](http://localhost:8080/reviews/cgiroux86/test/163#-MZEF4gQEIeIXwJp230O:-MZEfoUWEJcvQ9vb1pA8:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/660d1caa5c5683aba18672310d73155f7bd6b68e/mainfile1.js#L6)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another test
</blockquote></details>

Done.
___
*[mainfile1.js, line 9 at r7](http://localhost:8080/reviews/cgiroux86/test/163#-MZE7Wl-64WDRdiQ2NYy:-MZEfp773TAT0R9g720d:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/660d1caa5c5683aba18672310d73155f7bd6b68e/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Timestamp test
</blockquote></details>

Done.
___
*[newFile.js, line 1 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDdAdb0lKFloEydRYt:-MZEfqDkAMqHENHV50BQ:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Because maybe?
</blockquote></details>

Done.
___
*[newFile.js, line 1 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZEDqHy964byorOpSxh:-MZEft5OBENMZ7gbPJnk:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

No place I'd rather be.
</blockquote></details>

Done.
___
*[newFile.js, line 2 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDoMGw2Y6FInmPGEyW:-MZEfs_6AGSXRQrvDCjE:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/e8f366f5dc5f916751fa6c443f4f8c0c200fef71/newFile.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.
___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDfKT_C0sOxpTJ0Tyk:-MZEfplHCCuI-V6MwsOE:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Still running.
</blockquote></details>

Done.
___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDlL1T3ds7guH7oFtz:-MZEfq-d8ohZm7A5Ht2r:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

I don't know.
</blockquote></details>

Done.
___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZEA9YkAfXHuKMIfItS:-MZEfskQ9jaMDLmJY_6E:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another blocking disposition
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-27 11:53 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 14 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 3 at r7](http://localhost:8080/reviews/cgiroux86/test/163#-MZIAFQOAOGcGYvIUbLl:-MZIAFQPAglF13lx88-t:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/660d1caa5c5683aba18672310d73155f7bd6b68e/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

Test


<!-- Sent from Reviewable.io -->

2021-04-27 11:54 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 14 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-04-27 11:57 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/163)* status: all files reviewed, 14 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 3 at r5](http://localhost:8080/reviews/cgiroux86/test/163#-MZDlL1T3ds7guH7oFtz:-MZIBCKM0ikWpFS2lU1p:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/425836294f93af789d0f8f6b659448f02489f268/newFile.js#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-04-27 12:00 UTC, merged