PR#2
cgiroux86/test pull request #306
Opened 2021-07-12 14:14 UTC by cgiroux86

Test PR

2021-07-12 14:15 UTC, chg1017 requested changes
> Reviewed 1 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 1 unresolved discussion (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeQ3XCX2FZx4QdMMcQj:b7r5xui) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
Comment


<!-- Sent from Reviewable.io -->

2021-07-12 14:15 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeQ3auz5ilOTvALdvR7:b-8zijrq) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
> ```HTML
> <h1>Quod autem in homine praestantissimum atque optimum est, id deseruit.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Possumusne ergo in vita summum bonum dicere, cum id ne in cena quidem posse videamur? Duo Reges: constructio interrete. Suo genere perveniant ad extremum; </p>
> ```

Test comment 


<!-- Sent from Reviewable.io -->

2021-07-12 14:15 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeQ3dBt7ZQR84w-hnqk:bk0k3zo) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
> ```HTML
> <h1>Fortemne possumus dicere eundem illum Torquatum?</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. Videamus igitur sententias eorum, tum ad verba redeamus. Duo Reges: constructio interrete. Quod autem satis est, eo quicquid accessit, nimium est; Hoc autem tempore, etsi multa in omni parte Athenarum sunt in ipsis locis indicia summorum virorum, tamen ego illa moveor exhedra. Sit ista in Graecorum levitate perversitas, qui maledictis insectantur eos, a quibus de veritate dissentiunt. His enim rebus detractis negat se reperire in asotorum vita quod reprehendat. Utrum igitur tibi litteram videor an totas paginas commovere? Si enim sapiens aliquis miser esse possit, ne ego istam gloriosam memorabilemque virtutem non magno aestimandam putem. Et saepe officium est sapientis desciscere a vita, cum sit beatissimus, si id oportune facere possit, quod est convenienter naturae. Beatus autem esse in maximarum rerum timore nemo potest. Utilitatis causa amicitia est quaesita. </p>
> ```

Another test


<!-- Sent from Reviewable.io -->

2021-07-12 14:15 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[large/large_diff_68.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3fpC5tQ0BEkmTRH9:-MeQ3fpC5tQ0BEkmTRHA:b7b0mtm) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_68.html#L3)):*
> ```HTML
> <h1>Ita relinquet duas, de quibus etiam atque etiam consideret.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quo invento omnis ab eo quasi capite de summo bono et malo disputatio ducitur. In qua si nihil est praeter rationem, sit in una virtute finis bonorum; Duo Reges: constructio interrete. Sed erat aequius Triarium aliquid de dissensione nostra iudicare. Quod cum ita sit, perspicuum est omnis rectas res atque laudabilis eo referri, ut cum voluptate vivatur. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Cum sciret confestim esse moriendum eamque mortem ardentiore studio peteret, quam Epicurus voluptatem petendam putat. Is enim, qui occultus et tectus dicitur, tantum abest ut se indicet, perficiet etiam ut dolere alterius improbe facto videatur. Quid enim necesse est, tamquam meretricem in matronarum coetum, sic voluptatem in virtutum concilium adducere? At ille pellit, qui permulcet sensum voluptate. </p>
> ```

ANOTHER ONE...


<!-- Sent from Reviewable.io -->

2021-07-12 14:46 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeQAdcO-oL8aucCeZmR:b-4cuw9v) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test comment 
</blockquote></details>

Deferring


<!-- Sent from Reviewable.io -->

2021-07-12 14:46 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeQAgX0-lgya15soNKS:b-4cuzid) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Deferring
</blockquote></details>

Deferred?
___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeQ3nPZ1B_JdDNHn5TU:b-7rjd50) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
> ```HTML
> <h1>Magni enim aestimabat pecuniam non modo non contra leges, sed etiam legibus partam.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Iam illud quale tandem est, bona praeterita non effluere sapienti, mala meminisse non oportere? Hi curatione adhibita levantur in dies, valet alter plus cotidie, alter videt. Quid affers, cur Thorius, cur Caius Postumius, cur omnium horum magister, Orata, non iucundissime vixerit? Duo Reges: constructio interrete. Iudicia rerum in sensibus ponit, quibus si semel aliquid falsi pro vero probatum sit, sublatum esse omne iudicium veri et falsi putat. Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. At vero si ad vitem sensus accesserit, ut appetitum quendam habeat et per se ipsa moveatur, quid facturam putas? Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Itaque beatior Africanus cum patria illo modo loquens: Desine, Roma, tuos hostes reliquaque praeclare: Nam tibi moenimenta mei peperere labores. Longum est enim ad omnia respondere, quae a te dicta sunt. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. </p>
> ```

draft


<!-- Sent from Reviewable.io -->

2021-07-12 23:34 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS3gVz0NEscePVLIZh:byp337e) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Deferred?
</blockquote></details>

Reply?


<!-- Sent from Reviewable.io -->

2021-07-12 23:35 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeS3jPMCPSZ5HYLnJ45:bu5nrod) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another test
</blockquote></details>

Replying


<!-- Sent from Reviewable.io -->

2021-07-12 23:37 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS4FItC5fq0jZmb-C4:bu5nrod) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Replying


<!-- Sent from Reviewable.io -->

2021-07-12 23:37 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS4NVW764TO63iqCIA:b-81nndn) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Replying
</blockquote></details>

Reply


<!-- Sent from Reviewable.io -->

2021-07-12 23:38 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS4Wz72EeU8O55DARY:b-xpl9ut) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Reply
</blockquote></details>

Draft comment


<!-- Sent from Reviewable.io -->

2021-07-12 23:39 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS4ktf3fkqS3tD6sCF:b-j19ubl) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Draft comment
</blockquote></details>

Another draft


<!-- Sent from Reviewable.io -->

2021-07-12 23:40 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS52Sy1EjfpG01KGUC:be27qxa) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another draft
</blockquote></details>

A really big team


<!-- Sent from Reviewable.io -->

2021-07-12 23:42 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeS5LpC2arA6RmpZtcI:b-4o5vco) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

A really big team
</blockquote></details>

No strings


<!-- Sent from Reviewable.io -->

2021-07-12 23:43 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS5Xk70PElVsThvi7l:b-4cuw9v) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Reply?
</blockquote></details>

Deferring


<!-- Sent from Reviewable.io -->

2021-07-12 23:43 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeS5ZpT4S9RYQ-NV46T:b-w7iszf) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Replying
</blockquote></details>

DRAFT COMMENT 


<!-- Sent from Reviewable.io -->

2021-07-12 23:45 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6CRbBCvTKVmyvccK:b82gnsz) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Deferring
</blockquote></details>

DREAFT 


<!-- Sent from Reviewable.io -->

2021-07-12 23:46 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6K2q4xA4Hk_ZG56i:bz7tr1y) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DREAFT 
</blockquote></details>

DRAFTRTT


<!-- Sent from Reviewable.io -->

2021-07-12 23:47 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6XHf3WFW9Lrrln0X:b-ex84as) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DRAFTRTT
</blockquote></details>

ANOTHER ONE 


<!-- Sent from Reviewable.io -->

2021-07-12 23:48 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeS696D6mOuVwi8tB8m:bb6u0fs) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DRAFT COMMENT 
</blockquote></details>

DRAF
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6hBFEV-h56bdylkh:b8l3f7g) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER ONE 
</blockquote></details>

DEFERRED 


<!-- Sent from Reviewable.io -->

2021-07-12 23:48 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6ib4DH36-UpI7tBL:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DEFERRED 
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-07-12 23:48 UTC, cgiroux86 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS6r1D-eycrf2WPYi1:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-07-12 23:51 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS7Tc1Em2Lzt0GW2C2:byak5ir) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

PARKING


<!-- Sent from Reviewable.io -->

2021-07-12 23:52 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS7j4B8ER9cL5GosNP:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKING
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-12 23:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeS8ne73XHiN0MqMCSj:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-13 00:05 UTC, chg1017 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeSAk9NAnAsSmL3fatg:b-5insuk) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

No strings
</blockquote></details>

REPLIED


<!-- Sent from Reviewable.io -->

2021-07-13 00:05 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeSAmDy45HfOsW7X7pU:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPLIED
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-13 00:07 UTC, chg1017 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeSB4QF4CwnTpTB2jg3:b-828rh7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

draft
</blockquote></details>

REPLY


<!-- Sent from Reviewable.io -->

2021-07-13 00:07 UTC, chg1017 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeSB8eCESqDLcSY7w7x:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-13 00:07 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeSBACV4V9ED7OAPDhJ:b3g944a) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

REALLY PARK


<!-- Sent from Reviewable.io -->

2021-07-13 00:10 UTC, chg1017 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeSBtAq1kmNjoERYTpU:b-szzfb7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DRAF
</blockquote></details>

REPLYING


<!-- Sent from Reviewable.io -->

2021-07-13 00:12 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeSCC3n3RidlnnV53hb:b-szzfb7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

REPLYING
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeSCDQP3pc9e7vwd9Xt:b-828rgb) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REALLY PARK
</blockquote></details>

REPLy
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeSCE6e2N2Jan6Gql-C:b-828rh7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPLYING
</blockquote></details>

REPLY


<!-- Sent from Reviewable.io -->

2021-07-13 00:12 UTC, cgiroux86 commented
___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeSCFgl8xEzrn2XxhH_:b-828rh7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPLY
</blockquote></details>

REPLY


<!-- Sent from Reviewable.io -->

2021-07-13 00:12 UTC, cgiroux86 commented
___
*[large/large_diff_68.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3fpC5tQ0BEkmTRH9:-MeSCHU9542Qq2xAuQ0u:boznrgh) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_68.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

ANOTHER ONE...
</blockquote></details>

LAST ONE


<!-- Sent from Reviewable.io -->

2021-07-13 00:13 UTC, chg1017 commented
___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeSCRV-0XqwTSiyJh09:b-828rh7) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REPLY
</blockquote></details>

REPLY


<!-- Sent from Reviewable.io -->

2021-07-13 00:13 UTC, chg1017 requested changes
> Reviewed 150 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeSCUmR26TopIcmPLRW:bb71c33) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REPLYING
</blockquote></details>

PARK
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeSCVx27e-9qpqvKyJq:b-8bkasl) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REPLy
</blockquote></details>

AGAIN
___
*[large/large_diff_68.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3fpC5tQ0BEkmTRH9:-MeSCTZlBUog-17ekJDz:b-828rh7) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_68.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

LAST ONE
</blockquote></details>

REPLY


<!-- Sent from Reviewable.io -->

2021-07-13 00:14 UTC, chg1017 commented
___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeSCkIGEyye0iWC0H1e:b-7f9ol0) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REPLY
</blockquote></details>

DIRECT SENDF


<!-- Sent from Reviewable.io -->

2021-07-13 00:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeSCsNx0Il0Vn6f89Ms:by6wbtu) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

PARK
</blockquote></details>

REPARK


<!-- Sent from Reviewable.io -->

2021-07-13 00:16 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3auz5ilOTvALdvR6:-MeSD6dsDowsmjl7FZVf:bnvgncp) ([raw file](https://github.com/cgiroux86/test/blob/015628aaea6c3e883c75fa5c4a7256bd94a4905e/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

AGAIN
</blockquote></details>

ANOTHER PARKING LOT 


<!-- Sent from Reviewable.io -->

2021-07-13 12:02 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeUjeyb65B5dheW1cm-:bu5nrod) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPLY
</blockquote></details>

Replying


<!-- Sent from Reviewable.io -->

2021-07-13 12:02 UTC, cgiroux86 commented
___
*[large/large_diff_137.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3nPZ1B_JdDNHn5TT:-MeUjl6bBhrZIK9ru8Qv:b3jkk3f) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_137.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Replying
</blockquote></details>

DRAFT COMMENT


<!-- Sent from Reviewable.io -->

2021-07-13 12:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUk2mU4V5XqNlOTOFo:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REPARK
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-13 12:04 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUk97Y89L-BBSmNdl8:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-07-13 12:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUkF21Ew7p9qDgXD87:b-ex84as) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

ANOTHER ONE 


<!-- Sent from Reviewable.io -->

2021-07-13 12:07 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUkwfx-rmDzqg7q4Di:b7juzk9) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER ONE 
</blockquote></details>

LAST TEST 


<!-- Sent from Reviewable.io -->

2021-07-13 12:07 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUkzQX5kqDyBVWzVmq:b-nyr9cf) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

LAST TEST 
</blockquote></details>

DIRECT DRAFT 


<!-- Sent from Reviewable.io -->

2021-07-13 12:08 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUlFsl2ACbsuQWRFLG:bxc1hdq) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DIRECT DRAFT 
</blockquote></details>

ANOTHER


<!-- Sent from Reviewable.io -->

2021-07-13 12:42 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUsuFpE9qrhdGHrbhp:b3jkk3f) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER
</blockquote></details>

DRAFT COMMENT


<!-- Sent from Reviewable.io -->

2021-07-13 12:42 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_1.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3dBt7ZQR84w-hnqj:-MeUswuU0hNUXkXFndH6:b-jzmiuz) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_1.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

DIRECT SENDF
</blockquote></details>

ANOTHER MESSAGE


<!-- Sent from Reviewable.io -->

2021-07-13 12:43 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUt6OS2ZzCpivK0q5i:byak2b5) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DRAFT COMMENT
</blockquote></details>

PARKED?


<!-- Sent from Reviewable.io -->

2021-07-13 12:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUtOQi0V73r56STmO3:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKED
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-07-13 12:50 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUugAA9EORl0fVhH5Q:baz3vj8) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

ANOTHER ONE


<!-- Sent from Reviewable.io -->

2021-07-13 12:50 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUuhpO236Ltk00gbwc:byak5cx) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER ONE
</blockquote></details>

PARKIGN


<!-- Sent from Reviewable.io -->

2021-07-13 12:55 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUvuBD5frINwtW_TH1:b-3sz5na) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKIGN
</blockquote></details>

TEST COMMENT 


<!-- Sent from Reviewable.io -->

2021-07-13 12:55 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUw1rdEe1jtcysLrWo:b2nhiq4) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST COMMENT 
</blockquote></details>

LOT


<!-- Sent from Reviewable.io -->

2021-07-13 12:56 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUw3CgClA0wb_zxwZZ:bwo1f3d) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

LOT
</blockquote></details>

PROMISE?


<!-- Sent from Reviewable.io -->

2021-07-13 12:56 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUwEWgDQPgp1QWlhDS:br8o9ks) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PROMISE?
</blockquote></details>

COMMIT


<!-- Sent from Reviewable.io -->

2021-07-13 13:01 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUxKZP35UOkK-8D0uT:byak2cb) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

COMMIT
</blockquote></details>

PARKEDi


<!-- Sent from Reviewable.io -->

2021-07-13 13:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUxi0h3-Or7JkFndUU:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKEDi
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-07-13 13:04 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUxsC3CQxrnGwalFrS:b-ex84as) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

ANOTHER ONE 


<!-- Sent from Reviewable.io -->

2021-07-13 13:04 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeUxx7hCgqKnITN_Xdm:b-6mryip) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER ONE 
</blockquote></details>

LAST ONE 


<!-- Sent from Reviewable.io -->

2021-07-13 13:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeV-URQ2Ixn1sMf0HN8:byak5ir) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

LAST ONE 
</blockquote></details>

PARKING


<!-- Sent from Reviewable.io -->

2021-07-13 13:15 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeV-Vwt8rrO_52jF1kC:bm4p0ms) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

PARKING
</blockquote></details>

ANOTHER PARKED?


<!-- Sent from Reviewable.io -->

2021-07-13 13:18 UTC, chg1017 reviewed
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-07-13 13:40 UTC, cgiroux86 commented
___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeV5Axg-9xzmIwJTYmV:bx6ndqm) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

ANOTHER PARKED?
</blockquote></details>

PARKED


<!-- Sent from Reviewable.io -->

2021-07-13 13:41 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeV5MDt8yKeGhu-Mx-D:b-5jmmbr) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

REALLY PARKED
</blockquote></details>

PARKED BACK


<!-- Sent from Reviewable.io -->

2021-07-13 13:55 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[large/large_diff_128.html, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeV8ZltE_23-eoINZpJ:-MeV8ZltE_23-eoINZpK:bb720lr) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/large/large_diff_128.html#L5)):*
> ```HTML
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Audio equidem philosophi vocem, Epicure, sed quid tibi dicendum sit oblitus es. Cum autem negant ea quicquam ad beatam vitam pertinere, rursus naturam relinquunt. Ergo infelix una molestia, fellx rursus, cum is ipse anulus in praecordiis piscis inventus est? Bonum ipsum etiam quid esset, fortasse, si opus fuisset, definisses aut quod esset natura adpetendum aut quod prodesset aut quod iuvaret aut quod liberet modo. An obliviscimur, quantopere in audiendo in legendoque moveamur, cum pie, cum amice, cum magno animo aliquid factum cognoscimus? Duo Reges: constructio interrete. </p>
> 
> <h4>Esse enim quam vellet iniquus iustus poterat inpune.</h4>
> ```

Park


<!-- Sent from Reviewable.io -->

2021-07-13 14:27 UTC, chg1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 1 of 151 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/306#-MeQ3XCX2FZx4QdMMcQi:-MeVG3_g26Nu5GVhjHH_:by6wbtu) ([raw file](https://github.com/cgiroux86/test/blob/8ab65d927b2e688ffff39bd82e32e4fbfd746bdb/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

PARKED BACK
</blockquote></details>

REPARK


<!-- Sent from Reviewable.io -->

2021-07-13 14:34 UTC, chg1017 reviewed
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/306)* status: 2 of 151 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, @chg101786, and @girouxchris1017)



<!-- Sent from Reviewable.io -->

2021-07-13 14:50 UTC, merged