first commit
cgiroux86/test pull request #439
Opened 2021-11-03 17:47 UTC by cgiroux86

2021-11-03 17:47 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnauSxx7DWNioO6uYiI):*
First?


<!-- Sent from Reviewable.io -->

2021-11-03 17:48 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnauSxx7DWNioO6uYiI):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

First?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 17:49 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnault1AdnLEZpXnRV1:-Mnault1AdnLEZpXnRV2:b-srunom) ([raw file](https://github.com/cgiroux86/test/blob/3cb3b8f5ad90e3236947ade9fae90c38c1509017/added.py#L2)):*
> ```Python
> print('This is an added file!!!');
> print('TEST!!');
> ```

New comment


<!-- Sent from Reviewable.io -->

2021-11-03 17:49 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnault1AdnLEZpXnRV1:-Mnauw8h1wBHXPagF8Rm:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/3cb3b8f5ad90e3236947ade9fae90c38c1509017/added.py#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

New comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 17:52 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnault1AdnLEZpXnRV1:-MnavSSO3R0XJSwOnnK4:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/3cb3b8f5ad90e3236947ade9fae90c38c1509017/added.py#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 17:52 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnault1AdnLEZpXnRV1:-Mnav_FT2pQ1WoK8CJ0M:b2nhky0) ([raw file](https://github.com/cgiroux86/test/blob/3cb3b8f5ad90e3236947ade9fae90c38c1509017/added.py#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No.


<!-- Sent from Reviewable.io -->

2021-11-03 17:58 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnault1AdnLEZpXnRV1:-Mnax-PkEYzG7xJQlun6:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/3cb3b8f5ad90e3236947ade9fae90c38c1509017/added.py#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

No.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:00 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
New!


<!-- Sent from Reviewable.io -->

2021-11-03 18:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

New!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:03 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 18:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:05 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hello?


<!-- Sent from Reviewable.io -->

2021-11-03 18:10 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-MnaxQ6xDVm8CWHjv3_-):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hello?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:11 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
New!


<!-- Sent from Reviewable.io -->

2021-11-03 18:13 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

New!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:14 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sounds good.


<!-- Sent from Reviewable.io -->

2021-11-03 18:14 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:15 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not!


<!-- Sent from Reviewable.io -->

2021-11-03 18:17 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:20 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 18:21 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:21 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 18:23 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:25 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 18:26 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:26 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 18:26 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:27 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2021-11-03 18:55 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:56 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 18:58 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 19:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 19:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 19:18 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 19:18 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 19:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 19:58 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 20:06 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 20:08 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:09 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 20:09 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:10 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:12 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 20:12 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 20:13 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Another


<!-- Sent from Reviewable.io -->

2021-11-03 21:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:04 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 21:12 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:12 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:13 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 21:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:16 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 21:17 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:18 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 21:21 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:22 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:23 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:25 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:27 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 21:27 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 22:41 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 22:42 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 22:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 22:45 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 22:50 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 22:51 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 22:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 22:58 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 23:05 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:07 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:07 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:08 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:09 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:11 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:12 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:15 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:18 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:22 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 23:23 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:26 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NO?


<!-- Sent from Reviewable.io -->

2021-11-03 23:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

NO?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:45 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-03 23:48 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:51 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:52 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:53 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-03 23:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 23:58 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 00:00 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:01 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 00:02 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:03 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 00:04 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

NOT!


<!-- Sent from Reviewable.io -->

2021-11-04 00:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

NOT!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 00:08 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:10 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 00:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:12 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why?


<!-- Sent from Reviewable.io -->

2021-11-04 00:14 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why?
</blockquote></details>

DOn.e


<!-- Sent from Reviewable.io -->

2021-11-04 00:14 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DOn.e
</blockquote></details>

No sir.


<!-- Sent from Reviewable.io -->

2021-11-04 00:24 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

No sir.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:25 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No.


<!-- Sent from Reviewable.io -->

2021-11-04 00:40 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

No.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:41 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 00:42 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:43 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2021-11-04 00:43 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:44 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 00:46 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 00:46 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 02:05 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:06 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 02:07 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:11 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 02:14 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:15 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 02:15 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:16 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

WTF


<!-- Sent from Reviewable.io -->

2021-11-04 02:17 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

WTF
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:18 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-04 02:19 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:19 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 02:20 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 02:20 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2021-11-04 12:53 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 12:54 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/439)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/439#-Mnb--KO6ydh6ms1Us8E):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-04 16:12 UTC, merged