first commit
cgiroux86/test pull request #521
Opened 2022-02-15 13:13 UTC by cgiroux86

+reviewer:@chg1017
+@girouxchris1017
+bug

2022-02-22 17:10 UTC, cgiroux86 reviewed
![Screen Shot 2022-02-02 at 1.49.38 PM.png](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/wzdy6hLvaZ2wGOxo6tz99K2s/Screen%20Shot%202022-02-02%20at%201.49.38%20PM.png)

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521#-:-MwXPQLz3V-srQPB6Lmp:b-p9jurp)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chg1017)



<!-- Sent from Reviewable.io -->

2022-02-22 17:13 UTC, cgiroux86 reviewed
![Screen Shot 2022-02-02 at 1.49.38 PM.png](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/EVHobiX4K2kaH_tZGqNehUyy/Screen%20Shot%202022-02-02%20at%201.49.38%20PM.png)

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521#-:-MwXPzP42lVwAKGKbd7D:b2m1y8p)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chg1017)



<!-- Sent from Reviewable.io -->

2022-03-01 20:38 UTC, cgiroux86 commented
___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C2Dy8loz4CHGasxT:-Mx6C2Dy8loz4CHGasxU:b-mhdmyn) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L2)):*
> ```Python
> print('This is an added file!!!!');
> print('TEST!!!!');
> ```

omment


<!-- Sent from Reviewable.io -->

2022-03-01 20:38 UTC, cgiroux86 reviewed
![Screen Shot 2022-02-02 at 1.36.12 PM.png](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/-a-wERvgsVbkICzW_o2UCr4p/Screen%20Shot%202022-02-02%20at%201.36.12%20PM.png)

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521#-:-MwYYNiJ1nD0tw-A04Az:bw8h5bf)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C4FP5-zyIah97dar:-Mx6C4FP5-zyIah97das:b7r5xui) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L1)):*
> ```Python
> print('This is an added file!!!!');
> ```

Comment


<!-- Sent from Reviewable.io -->

2022-03-03 01:30 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxBrB2V86pyjXv_WQAs):*
Test
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C4FP5-zyIah97dar:-Mx6rs5iCu-5K_xqPSCZ:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Test
___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C2Dy8loz4CHGasxT:-Mx6rua8Dd7Q7nklQPcz:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

omment
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2022-03-03 01:42 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxBrB2V86pyjXv_WQAs):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C4FP5-zyIah97dar:-MxCRLjO45bcqmlijLjA:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 01:43 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C2Dy8loz4CHGasxT:-MxCRRsX1ihsrY0ErhDX:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 01:44 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxBrB2V86pyjXv_WQAs):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C4FP5-zyIah97dar:-MxCReKO3IksqwPa4eGI:bb7110x) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?
___
*[added.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-Mx6C2Dy8loz4CHGasxT:-MxCRcISBcoCfGe5xJW-:bb7110x) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2022-03-03 19:10 UTC, cgiroux86 commented
TESTING





<!-- Sent from Reviewable.io -->

2022-03-04 17:18 UTC, cgiroux86 commented
COMMENT

2022-03-04 17:19 UTC, cgiroux86 commented
This is a test





<!-- Sent from Reviewable.io -->

2022-03-04 17:37 UTC, cgiroux86 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521#-:-MxL-7Dy60p1UVPxXRMg:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)



<!-- Sent from Reviewable.io -->

2022-03-04 17:40 UTC, cgiroux86 commented
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/521#-MxL04_j98872t-JUWu3:-MwbVgaB2UXSnUFezJug:beu4iyi) (no related file):*
![Screen Shot 2022-02-01 at 5.11.25 PM.png](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/Z2ssg56QryyusADIzdILWwwU/Screen%20Shot%202022-02-01%20at%205.11.25%20PM.png)

---


<!-- Sent from Reviewable.io -->

2022-03-04 17:42 UTC, cgiroux86 commented
TESTING!





<!-- Sent from Reviewable.io -->

2022-03-04 18:48 UTC, cgiroux86 commented on added.py
> +print('TEST!!!!');
Comment!

2022-03-04 18:53 UTC, cgiroux86 reviewed
TEST

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521#-:-MxLBs64BhIqb1rJacCh:bb73z13)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)



<!-- Sent from Reviewable.io -->

2022-03-04 18:54 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxBrB2V86pyjXv_WQAs):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

COMMENT!


<!-- Sent from Reviewable.io -->

2022-03-04 19:01 UTC, girouxchris1017 commented on added.py
> +print('TEST!!!!');
Comment!

2022-03-04 19:03 UTC, girouxchris1017 commented on added.py
> -print('TEST!!!');
Comment!

2022-03-04 19:04 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxLJNx10LTtG9iylErk):*
Comment!


<!-- Sent from Reviewable.io -->

2022-03-04 19:05 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/521#-MxLJXt9CMD6GJZRklKX:-MxLJXt9CMD6GJZRklKY:b-kbdio7) ([raw file](https://github.com/cgiroux86/test/blob/d4a44dbd15035e2a4d1e2b6232aecf2cb18cd112/added.py#L1)):*
> ```Python
> print('This is an added file!!!!');
> ```

COMMENTING!


<!-- Sent from Reviewable.io -->

2022-03-04 19:14 UTC, cgiroux86 commented on added.py
> -print('TEST!!!');
COMMENTING!

2022-03-04 19:15 UTC, cgiroux86 commented on added.py
> +print('TEST!!!!');
Comment!

2022-03-08 18:31 UTC, cgiroux86 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-03-08 18:51 UTC, cgiroux86 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-03-08 18:53 UTC, cgiroux86 commented
This is a test





<!-- Sent from Reviewable.io -->

2022-03-08 19:36 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/521)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/521#-MxevBnP8sOWYYH3NMMF:-MxejeEy5vT_58tP5w_s:bmrzlax) (no related file):*
![Screen Shot 2021-10-01 at 11.13.17 AM.png](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/be7mAm4-QCfDCn-NqQ1FBfbp/Screen%20Shot%202021-10-01%20at%2011.13.17%20AM.png)

---


<!-- Sent from Reviewable.io -->

2022-03-09 15:15 UTC, cgiroux86 commented
T





<!-- Sent from Reviewable.io -->

2022-03-09 15:15 UTC, cgiroux86 commented
This is a test draft





<!-- Sent from Reviewable.io -->

2022-03-09 15:50 UTC, cgiroux86 commented
this





<!-- Sent from Reviewable.io -->

2022-03-09 16:16 UTC, cgiroux86 commented
This is a test draft





<!-- Sent from Reviewable.io -->

2022-03-09 16:28 UTC, cgiroux86 commented
Test draft





<!-- Sent from Reviewable.io -->

2022-03-09 16:28 UTC, cgiroux86 commented
Test draft





<!-- Sent from Reviewable.io -->

2022-03-09 16:29 UTC, cgiroux86 commented
Test draft





<!-- Sent from Reviewable.io -->

2022-03-09 16:58 UTC, cgiroux86 commented
TEST





<!-- Sent from Reviewable.io -->

2022-03-15 16:35 UTC, cgiroux86 commented
testing!





<!-- Sent from Reviewable.io -->

2022-03-28 12:53 UTC, merged